ruoyi: 
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /dat/upload

# token配置
token:
  # 令牌密钥
  secret: cc2bcf28d9ffc17fcbf169f3325607bb

# 数据源配置
spring:
  # redis 配置
  redis:
    # 地址
    host: 10.206.16.12
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: DAT@ProdRedis147
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.206.16.12:3306/dat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: DAT@ProdMysql147
