ruoyi: 
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /dat/upload
  echarts:
    api: http://10.206.16.13:3000

wx:
  mp:
    configs:
      - appId: wxb5930c3148e86017
        secret: 6cb08aec1c895b67a66fb174fba96d8f

# 数据源配置
spring:
  # redis 配置
  redis:
    # 地址
    host: 10.206.16.13
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: DAT@TestRedis147
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.206.16.13:3306/dat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: DAT@TestMysql147
      